#+TITLE: Explosives and Distinguishers
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="myStyle.css" />
#+OPTIONS: html-style:nil H:1 num:nil
#+HTML_LINK_HOME: index.html

/*Abstract.* TODO/ Testing

/Quick interjection:/ This piece contains (too) many proofs in [[https://docs.racket-lang.org/pie/index.html][Pie]], a simple, beautiful, but
verbose dependently typed programming language.  Before getting
Here's a small logical interface used throughout to make
proofs more readable:

#+begin_src lisp
  #lang pie

  (claim âŠ¥ U)
  (define âŠ¥ Absurd)

  (claim âŠ¤ U)
  (define âŠ¤ Trivial)

  (claim Â¬ (â†’ U U))
  (define Â¬ (Î» (A) (â†’ A âŠ¥)))

  (claim âˆ§ (â†’ U U U))
  (define âˆ§ (Î» (A B) (Pair A B)))

  (claim âˆ¨ (â†’ U U U))
  (define âˆ¨ (Î» (A B) (Either A B)))

  (claim â†” (â†’ U U U))
  (define â†” (Î» (A B) (âˆ§ (â†’ A B) (â†’ B A))))

  (claim â‰  (Î  ((A U)) (â†’ A A U)))
  (define â‰  (Î» (A x y) (Â¬ (= A x y))))
#+end_src

/Interjection over./

I recently spent an inordinate amount of time thinking about [[https://docs.racket-lang.org/pie/index.html][Pie]]
formalizations of the following theorem:

#+begin_quote
/1 = 0 implies I am the Pope./
#+end_quote

I was interested primarily in proofs that could be carried out in the
minimal fragment of Pie, i.e., without the use of [[https://docs.racket-lang.org/pie/index.html#%28def._%28%28lib._pie%2Fmain..rkt%29._ind-.Absurd%29%29][~ind-Absurd~]], the
induction principle for the empty type which expresses the [[https://en.wikipedia.org/wiki/Principle_of_explosion][principle
of explosion]].

Thinking about this long enough leads invariably to a standard fact of
constructive mathematics: 1 = 0 is /explosive/ in the sense that
anything follows from it in the minimal fragment of Pie.[fn::See
Proposition 3.2 of Constructivism in Mathematics by Trolestra and van
Dalen.]

#+begin_src lisp
  (claim explode-1=0
    (â†’ (= Nat 1 0) (Î  ((A U)) A)))
  (define explode-1=0
    (Î» (1=0 A)
       (replace
         1=0
         (Î» (a) (which-Nat a A (Î» (_) âŠ¤)))
         sole)))
#+end_src

And thinking about for too long leads to a natural enough question:
/which equalities are explosive?/

* Distinguishers

Its straightforward to generalize the above proof to any fixed pair of
natural numbers.

#+begin_src
  (claim sub1 (â†’ Nat Nat))
  (define sub1
    (Î» (n)
       (which-Nat n 0 (Î» (n-1) n-1))))

  (claim âˆ¸ (â†’ Nat Nat Nat))
  (define âˆ¸
    (Î» (m n)
       (iter-Nat n m sub1)))

  (claim 5=7â†’1=0
    (â†’ (= Nat 5 7) (= Nat 1 0)))
  (define 5=7â†’1=0
    (Î» (5=7)
       (symm
         (cong
           5=7
  	 (the
  	   (â†’ Nat Nat)
  	   (Î» (n) (âˆ¸ n 6)))))))

  (claim explode-5=7
    (â†’ (= Nat 5 7) (Î  ((A U)) A)))
  (define explode-5=7
    (Î» (5=7)
       (explode-1=0 (5=7â†’1=0 5=7))))
#+end_src

It also works for the equality true = false, given the standard sum
type encoding of Booleans.

#+begin_src lisp
  (claim Bool U)
  (define Bool (Either âŠ¤ âŠ¤))

  (claim true Bool)
  (define true (left sole))

  (claim false Bool)
  (define false (right sole))

  (claim ind-Bool
    (Î  ((target Bool)
        (motive (â†’ Bool U))
        (true-case (motive true))
        (false-case (motive false)))
       (motive target)))
  (define ind-Bool
    (Î» (target motive true-case false-case)
       (ind-Either
         target
         motive
         (Î» (_) true-case)
         (Î» (_) false-case))))

  (claim boolâ†’nat (â†’ Bool Nat))
  (define boolâ†’nat
    (Î» (b) (ind-Bool b (Î» (_) Nat) 1 0)))

  (claim true=falseâ†’1=0
    (â†’ (= Bool true false) (= Nat 1 0)))
  (define true=falseâ†’1=0
    (Î» (true=false) (cong true=false boolâ†’nat)))

  (claim explode-true=false
    (â†’ (= Bool true false) (Î  ((A U)) A)))
  (define explode-true=false
    (Î» (true=false)
       (explode-1=0 (true=falseâ†’1=0 true=false))))
#+end_src

All we're doing here is bootstrapping; if an equality implies that 1 =
0 then it's explosive.  This condition is a tad clunky, but it hints
at a definition: let's say boolean function ğ‘“ : ğ´ â†’ Bool
/distinguishes/ two values ğ‘ and ğ‘ if ğ‘“ ğ‘ is true and ğ‘“ ğ‘ is false.
Let's also say ğ‘ and ğ‘ are /distinguishable/, written ğ‘ â—‡ ğ‘, if there
is a distinguisher for them.

#+begin_src lisp
  (claim Distinguishes
    (Î  ((A U)
        (f (â†’ A Bool)))
       (â†’ A A U)))
  (define Distinguishes
    (Î» (_ f x y)
       (âˆ§ (= Bool (f x) true)
          (= Bool (f y) false))))

  (claim â—‡
    (Î  ((A U))
       (â†’ A A U)))
  (define â—‡
    (Î» (A x y)
       (Î£ ((f (â†’ A Bool)))
          (Distinguishes A f x y))))

  ; the following are getters for â—‡

  (claim distinguisher-â—‡
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (â†’ A Bool)))
  (define distinguisher-â—‡
    (Î» (_ _ _ xâ—‡y)
       (car xâ—‡y)))

  (claim distinguishes-fst
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (= Bool
          (distinguisher-â—‡ A x y xâ—‡y x)
          true)))
  (define distinguishes-fst
    (Î» (_ _ _ xâ—‡y)
       (car (cdr xâ—‡y))))

  (claim distinguishes-snd
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (= Bool
          (distinguisher-â—‡ A x y xâ—‡y y)
          false)))
  (define distinguishes-snd
    (Î» (_ _ _ xâ—‡y)
       (cdr (cdr xâ—‡y))))
#+end_src

Being distinguishable captures more generally what's going on in the
case of 5 = 7 and true = false.

#+begin_src lisp
  (claim â—‡â†’explodeâ¼
    (Î  ((A U)
        (x A)
        (y A))
       (â†’ (â—‡ A x y)
          (= A x y)
          (Î  ((B U)) B))))
  (define â—‡â†’explodeâ¼
    (Î» (A x y xâ—‡y x=y)
      (explode-true=false
        (trans
          ; true = f x
          (symm (distinguishes-fst A x y xâ—‡y))
          (trans
            ; f x = f y
            (cong x=y (distinguisher-â—‡ A x y xâ—‡y))
            ; f y = false
            (distinguishes-snd A x y xâ—‡y))))))
#+end_src

In other words, /any equality of distinguishable terms is explosive./

* Inequality

Being distinguishable is a strictly stronger relation than inquality
in the minimal fragment of Pie.[fn::Moving forward, we'll take
advantage of the fact that the principle of explosion is not a theorem
in the minimal fragment of Pie: to show that any other claim is not a
theorem, it suffices to show that it implies explosion.]

#+begin_src lisp
  (claim â—‡â†’â‰ 
    (Î  ((A U)
        (x A)
        (y A))
       (â†’ (â—‡ A x y)
          (â‰  A x y))))
  (define â—‡â†’â‰ 
    (Î» (A x y xâ—‡y x=y)
       (â—‡â†’explodeâ¼ A x y xâ—‡y x=y âŠ¥)))

  (claim âŸ¨â‰ â†’â—‡âŸ©â†’ind-âŠ¥
    (â†’ (Î  ((A U)
           (x A)
           (y A))
          (â†’ (â‰  A x y)
             (â—‡ A x y)))
       (â†’ âŠ¥ Î  ((A U)) A))))
  (define âŸ¨â‰ â†’â—‡âŸ©â†’ind-âŠ¥
    (Î» (â‰ â†’â—‡ absurd)
       (â—‡â†’explodeâ¼
         âŠ¤
         sole
         sole
         (â‰ â†’â—‡
           âŠ¤
  	 sole
  	 sole
  	 (Î» (_) absurd))
         (same sole))))
#+end_src

The principle â‰ â†’â—‡ has the flavor of many well-studied semi-classical
principles: it expresses the ability to extract something constructive
from a negation proof.[fn::See, for example, Proposition 2.1.1 in
[[https://arxiv.org/abs/1804.05495][Constructive Reverse Mathematics]] by Hannes Diener. Actually, just read
the whole thing, it's very good.]  So it's not surprising that we
can't prove â‰ â†’â—‡ in Pie[fn::Said another way, we can't prove ind-âŠ¥â†’â‰ â†’â—‡
in the minimal fragment of Pie.] but we also can't disprove it.  This
is because â‰ â†’â—‡ is a theorem in the classical extension of Pie (which
is consistent).

That â‰ â†’â—‡ holds classically is not immediately obivous, but becomes
more clear through the lens of /decidable equality/.  In Pie, *if ğ´
admits decidable equality, then unequal values of type ğ´ are
distinguishable.*

And how does /that/ work?  This is also not immediately obvious.  It's
easy to forget that decidability, though core to constructive type
theory, has its origins in computability theory.

* Decidability

A type ğ´ admits *decidable equality* if for any two values ğ‘â‚ and ğ‘â‚‚
of type ğ´, we have ğ‘â‚ = ğ‘â‚‚ or ğ‘â‚ â‰  ğ‘â‚‚.  This can be seen as a
restriction of the law of excluded middle, so all types admit
decidable equality in the classical extension of Pie.

The computability theoretic notion of decidability is slightly
different: a predicate ğ‘ƒ is *decidable* if there is a computable
function ğ‘“ such that ğ‘“(ğ‘¥) = 1 if and only if ğ‘ƒ(ğ‘¥) holds.

/How do these two notions correspond?/ Answering this question
requires putting on our Curry-Howard glasses: a term ğ‘“ of type

#+begin_quote
~(Î  ((x A) (y A)) (âˆ¨ (= ğ´ ğ‘â‚ ğ‘â‚‚) (â‰  ğ´ ğ‘â‚ ğ‘â‚)))~
#+end_quote

on the one hand is a prove that ğ´ admits decidable equality.  On the
other hand, it's a /computable function/ where (ğ‘“ ğ‘ ğ‘) evaluates to a
left term if ğ‘ = ğ‘ and a right term otherwise.  Since we can determine
leftness versus rightness programmatically, the term ğ‘“ can be made a
decider for equality in the computability theoretic sense.

We'll formalize this observation, but first, a bit more on the general
framework of decidability.  A type ğ´ (viewed through the Curry-Howard
lens) is *decidable* if either ğ´ or Â¬ğ´ holds.  The law of excluded
middle is equivalent to every type being decidable.  We can lift this
notion of decidability to binary predicates, but if we want to use
those predicates in their Curried form, we'll need to uncurry when
reasoning about their decidability.

#+begin_src
(claim Dec (â†’ U U))
(define Dec
  (Î» (A) (âˆ¨ A (Â¬ A))))

(claim Decá´¾
  (Î  ((A U)
      (P (â†’ A U)))
     U))
(define Decá´¾
  (Î» (A P)
     (Î  ((x A)) (Dec (P x)))))

(claim Uncurryá´¾
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     (â†’ (Pair A B) U)))
(define Uncurryá´¾
  (Î» (_ _ P p)
     (P (car p) (cdr p))))

(claim Decá´¾Â²
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     U))
(define Decá´¾Â²
  (Î» (A B P)
     (Decá´¾ (Pair A B) (Uncurryá´¾ A B P))))

(claim Decâ¼ (â†’ U U))
(define Decâ¼
  (Î» (A)
     (Decá´¾Â²
       A
       A
       (Î» (x y) (= A x y)))))
#+end_src

We express the computability theoretic notion of decidability as
having a decider, i.e., a function that witnesses the truth value of
the predicate (we'll use ~true~ and ~false~ instead of ~1~ and ~0~).

#+begin_src
(claim Decides
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U)))
     U))
(define Decides
  (Î» (A f P)
     (Î  ((x A))
        (â†” (P x)
	   (= Bool (f x) true)))))

(claim Decider
  (Î  ((A U)
      (P (â†’ A U)))
     U))
(define Decider
  (Î» (A P)
     (Î£ ((f (â†’ A Bool)))
        (Decides A f P))))

(claim uncurry
  (Î  ((A U)
      (B U)
      (C U))
     (â†’ (â†’ A B C)
        (â†’ (Pair A B) C))))
(define uncurry
  (Î» (_ _ _ f p)
     (f (car p) (cdr p))))

(claim Decidesâ‚‚
  (Î  ((A U)
      (B U)
      (f (â†’ A B Bool))
      (P (â†’ A B U)))
     U))
(define Decidesâ‚‚
  (Î» (A B f P)
     (Decides
       (Pair A B)
       (uncurry A B Bool f)
       (Uncurryá´¾ A B P))))

(claim Deciderâ‚‚
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     U))
(define Deciderâ‚‚
  (Î» (A B P)
     (Î£ ((f (â†’ A B Bool)))
        (Decidesâ‚‚ A B f P))))

(claim Decidesâ¼
  (Î  ((A U)
      (f (â†’ A A Bool)))
     U))
(define Decidesâ¼
  (Î» (A f)
     (Decidesâ‚‚
       A
       A
       f
       (Î» (x y) (= A x y)))))

(claim Deciderâ¼ (â†’ U U))
(define Deciderâ¼
  (Î» (A)
     (Î£ ((f (â†’ A A Bool)))
        (Decidesâ¼ A f))))
#+end_src

As noted above, types that admit decidable equalities have an
"obvious" decider, i.e., the one encoded in the proof of decidability.

#+begin_src
(claim left?
  (Î  ((A U)
      (B U))
     (â†’ (Either A B)
        Bool)))
(define left?
  (Î» (_ _ e)
     (ind-Either
       e
       (Î» (_) Bool)
       (Î» (_) true)
       (Î» (_) false))))

(claim ?
  (Î  ((A U)
      (P (â†’ A U)))
     (â†’ (Decá´¾ A P) A Bool)))
(define ?
  (Î» (_ P decá´¾ x)
     (left?
       (P x)
       (Â¬ (P x))
       (decá´¾ x))))

(claim ?â‚‚
  (Î  ((A U)
      (B U)
      (P (â†’ A B U))
      (decá´¾Â² (Decá´¾Â² A B P)))
     (â†’ A B Bool)))
(define ?â‚‚
  (Î» (A B P decá´¾Â² x y)
     (?
       (Pair A B)
       (Uncurryá´¾ A B P)
       decá´¾Â²
       (cons x y))))

(claim â‰Ÿ
  (Î  ((A U))
     (â†’ (Decâ¼ A) A A Bool)))
(define â‰Ÿ
  (Î» (A) (?â‚‚ A A (Î» (x y) (= A x y)))))
#+end_src

We can convert the equality decider into an /distinguisher/ by
partially applying it: if (ğ‘“ ğ‘ ğ‘) is true if and only if ğ‘ = ğ‘, then
((ğ‘“ ğ‘) ğ‘¥) is true if ğ‘¥ = ğ‘ and false otherwise.  But the fact that
this holds depends crucially on the principle of explosion.

#+begin_src lisp
(claim ind-âŠ¥â†’decâ¼â†’â‰ â†’â—‡
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (decâ¼ (Decâ¼ A))
         (x A)
         (y A))
        (â†’ (â‰  A x y) (â—‡ A x y)))))
(define ind-âŠ¥â†’decâ¼â†’â‰ â†’â—‡
  (Î» (ind-âŠ¥ A decâ¼ x y xâ‰ y)
     (cons
       (â‰Ÿ A decâ¼ x)
       (cons
         (ind-Either
	   (decâ¼ (cons x x))
	   (Î» (e)
	      (= Bool
	         (left?
		   (= A x x)
		   (â‰  A x x)
		   e)
		 true))
           (Î» (_) (same true))
	   (Î» (xâ‰ x)
	      (ind-âŠ¥
	        (xâ‰ x (same x))
	        (= Bool false true))))
	 (ind-Either
	   (decâ¼ (cons x y))
	   (Î» (e)
	      (= Bool
	         (left?
		   (= A x y)
		   (â‰  A x y)
		   e)
		 false))
            (Î» (x=y) (ind-âŠ¥ (xâ‰ y x=y) (= Bool true false)))
	    (Î» (_) (same false)))))))

(claim âŸ¨decâ¼â†’â‰ â†’â—‡âŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (decâ¼ (Decâ¼ A))
         (x A)
         (y A))
        (â†’ (â‰  A x y) (â—‡ A x y)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨decâ¼â†’â‰ â†’â—‡âŸ©â†’ind-âŠ¥
  (Î» (decâ¼â†’â‰ â†’â—‡ absurd)
     (â—‡â†’explodeâ¼
       âŠ¤
       sole
       sole
       (decâ¼â†’â‰ â†’â—‡
         âŠ¤
         (Î» (_) (right (Î» (_) absurd)))
         sole
         sole
         ; artificial negation proof
         (Î» (_) absurd))
       (same sole))))
#+end_src

Another theme is made visible here: in almost all cases, the ~Trivial~
type is sufficient to find a counterexample in the minimal fragment
Pie of a given principle.  And usually this comes down to an
artificial proof of a negation using our ~Absurd~ assumption (see
above).

As a corollary, we can prove â‰ â†’â—‡ in the classical and constructive
(i.e., vanilla Pie) settings.

#+begin_src lisp
  (claim decâ¼â†’â‰ â†’â—‡
    (Î  ((A U)
        (decâ¼ (Decâ¼ A))
        (x A)
        (y A))
       (â†’ (â‰  A x y) (â—‡ A x y))))
  (define decâ¼â†’â‰ â†’â—‡
    (Î» (A decâ¼ x y xâ‰ y)
       (ind-âŠ¥â†’decâ¼â†’â‰ â†’â—‡
         ; explicit use of ind-Absurd
         (Î» (absurd A) (ind-Absurd absurd A))
         A
         decâ¼
         x
         y
         xâ‰ y)))

  ; postulating the law of excluded middle
  (claim lem (Î  ((A U)) (âˆ¨ A (Â¬ A))))
  (define lem TODO)

  (claim â‰ â†’â—‡-classical
    (Î  ((A U)
        (x A)
        (y A))
       (â†’ (â‰  A x y) (â—‡ A x y))))
  (define â‰ â†’â—‡-classical
    (Î» (A x y xâ‰ y)
       (decâ¼â†’â‰ â†’â—‡
         A
         (Î» (p) (lem (= A (car p) (cdr p))))
         x
         y
         xâ‰ y)))
#+end_src

* Deciders

But what about the minimal fragment?  We can't prove â‰ â†’â—‡ from
decidable equality, but we also can't even prove that the obvious
decider is /actually/ a decider.  In minimal Pie, having a decider (in
the sense that the obvious decider is, in fact, a decider) is a
stronger condition than admitting decidable equality.

One direction is easy: if a predicate ğ‘ƒ has a decider, then it's
decidable.  The proof: given ğ‘¥, ask the decider if ğ‘ƒ(ğ‘¥) or Â¬ğ‘ƒ(ğ‘¥).  We
break the proof up into two parts because working with Î£-types in Pie
isn't so ergonomic.

#+begin_src
(claim decidesâ†’decá´¾-helper
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U))
      (x A))
     (â†’ (â†” (P x) (= Bool (f x) true))
        (Dec (P x)))))
(define decidesâ†’decá´¾-helper
  (Î» (_ f P x)
     (ind-Bool
       (f x)
       (Î» (b)
          (â†’ (â†” (P x) (= Bool b true))
	     (Dec (P x))))
       (Î» (prf)
          (left ((cdr prf) (same true))))
       (Î» (prf)
          (right
	    (Î» (px)
	       (trueâ‰ false
	         (symm ((car prf) px)))))))))

(claim deciderâ†’decá´¾
  (Î  ((A U)
      (P (â†’ A U)))
     (â†’ (Decider A P)
        (Decá´¾ A P))))
(define deciderâ†’decá´¾
  (Î» (A P decider x)
     (decidesâ†’decá´¾-helper
       A
       (car decider)
       P
       x
       ((cdr decider) x))))
#+end_src

The more difficult direction is to show that if ğ‘ƒ is decidable then it
has a decider.  Though difficult is not quite right.  The proof is
very natural: the obvious decider for ğ‘ƒ is a decider. But within the
minimal fragment, we can't prove this.

Let's break this into two observations: within the minimal fragment,
if we know the value of the obvious decider on ğ‘, then we /can/ derive
proofs of the ğ‘ƒ(ğ‘) or Â¬ğ‘ƒ(ğ‘), depending on that value.

#+begin_src
(claim p?=trueâ†’p
  (Î  ((A U)
      (P (â†’ A U))
      (decá´¾ (Decá´¾ A P))
      (x A))
     (â†’ (= Bool (? A P decá´¾ x) true)
        (P x))))
(define p?=trueâ†’p
  (Î» (_ P decá´¾ x)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (â†’ (= Bool
	        (left? (P x) (Â¬ (P x)) e)
	        true)
             (P x)))
       (Î» (px _) px)
       (Î» (_ false=true)
          (explode-true=false
	    (symm false=true)
	    (P x))))))

(claim p?=falseâ†’Â¬p
  (Î  ((A U)
      (P (â†’ A U))
      (decá´¾ (Decá´¾ A P))
      (x A))
     (â†’ (= Bool
           (? A P decá´¾ x)
	   false)
        (Â¬ (P x)))))
(define p?=falseâ†’Â¬p
  (Î» (_ P decá´¾ x)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (â†’ (= Bool
	        (left? (P x) (Â¬ (P x)) e)
		false)
             (Â¬ (P x))))
       (Î» (_ true=false)
          (explode-true=false
	    true=false
	    (Â¬ (P x))))
       (Î» (Â¬px _) Â¬px))))
#+end_src

What we /can't/ do within the minimal fragment is determine the value
of the decider itself given ğ‘ƒ(ğ‘) or Â¬ğ‘ƒ(ğ‘), e.g., ğ‘ƒ(ğ‘) implies the
equality (? ğ‘ƒ ğ‘) = true given the principle of explosion, but this
implication also /implies/ the principle of explosion.  This
ultimately comes down to the fact that there isn't much we can do in
the Â¬ğ‘ƒ(ğ‘) branch of the decidability of ğ‘ƒ except explode it with our
assumption ğ‘ƒ(ğ‘).

#+begin_src lisp
(claim ind-âŠ¥â†’pâ†’p?=true
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (P x)
	   (= Bool
	      (? A P decá´¾ x)
	      true)))))
(define ind-âŠ¥â†’pâ†’p?=true
  (Î» (ind-âŠ¥ _ P decá´¾ x px)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (= Bool
	     (left? (P x) (Â¬ (P x)) e)
	     true))
       (Î» (_) (same true))
       (Î» (Â¬px)
          (ind-âŠ¥â†’explode
	    ind-âŠ¥
	    (P x)
            Â¬px
	    px
	    (= Bool false true))))))

(claim âŸ¨pâ†’p?=trueâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (P x)
	   (= Bool
	      (? A P decá´¾ x)
	      true)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨pâ†’p?=trueâŸ©â†’ind-âŠ¥
  (Î» (pâ†’p?=true absurd)
     (explode-true=false
       (symm
         (pâ†’p?=true
           âŠ¤
           (Î» (_) âŠ¤)
           (Î» (_) (right (Î» (_) absurd)))
           sole
           sole)))))

(claim ind-âŠ¥â†’Â¬pâ†’p?=false
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (Â¬ (P x))
	   (= Bool
	      (? A P decá´¾ x)
	      false)))))
(define ind-âŠ¥â†’Â¬pâ†’p?=false
  (Î» (ind-âŠ¥ _ P decá´¾ x Â¬px)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (= Bool
	     (left? (P x) (Â¬ (P x)) e)
	     false))
       (Î» (px)
          (ind-âŠ¥â†’explode
	    ind-âŠ¥
	    (P x)
	    Â¬px
	    px
	    (= Bool true false)))
       (Î» (_) (same false)))))

(claim âŸ¨Â¬pâ†’p?=falseâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (Â¬ (P x))
	   (= Bool
	      (? A P decá´¾ x)
	      false)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨Â¬pâ†’p?=falseâŸ©â†’ind-âŠ¥
  (Î» (Â¬pâ†’p?=false absurd)
     (explode-true=false
       (Â¬pâ†’p?=false
         âŠ¤
	 (Î» (_) âŠ¥)
	 (Î» (_) (left absurd))
	 sole
	 (Î» (absurd) absurd)))))
#+end_src

This inability to determine the value of the decider implies our
inability to prove that the obvious decider decides.

#+begin_src
(claim ind-âŠ¥â†’decá´¾â†’decides
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P)))
	(Decides A (? A P decá´¾) P))))
(define ind-âŠ¥â†’decá´¾â†’decides
  (Î» (ind-absurd A P decá´¾ x)
     (cons
       (ind-âŠ¥â†’pâ†’p?=true
         ind-absurd
	 A
	 P
	 decá´¾
	 x)
       (p?=trueâ†’p
         A
	 P
	 decá´¾
	 x))))

(claim ind-âŠ¥â†’decá´¾â†’decider
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P)))
	(Decider A P))))
(define ind-âŠ¥â†’decá´¾â†’decider
  (Î» (ind-âŠ¥ A P decá´¾)
     (cons
       (? A P decá´¾)
       (ind-âŠ¥â†’decá´¾â†’decides
         ind-âŠ¥
	 A
	 P
	 decá´¾))))

(claim âŸ¨decá´¾â†’decidesâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P)))
	(Decides A (? A P decá´¾) P))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨decá´¾â†’decidesâŸ©â†’ind-âŠ¥
  (Î» (decá´¾â†’decides absurd)
     (explode-true=false
       (symm
         ((car
	    ((decá´¾â†’decides
	       âŠ¤
	       (Î» (_) âŠ¤)
	       (Î» (_) (right (Î» (_) absurd))))
	      sole))
	    sole)))))
#+end_src

But, alas, even though having a decider is stronger condition in
minimal Pie, it's not sufficient to distinguish unequals.

#+begin_src
(claim âŸ¨deciderâ¼â†’â‰ â†’â—‡âŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (deciderâ¼ (Deciderâ¼ A))
	 (x A)
	 (y A))
	(â†’ (â‰  A x y) (â—‡ A x y)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨deciderâ¼â†’â‰ â†’â—‡âŸ©â†’ind-âŠ¥
  (Î» (deciderâ¼â†’â‰ â†’â—‡ absurd)
     (â—‡â†’explodeâ¼
       Trivial
       sole
       sole
       (deciderâ¼â†’â‰ â†’â—‡
         Trivial
	 (cons
	   (Î» (_ _) true)
	   (Î» (p)
  	     (cons
  	       (Î» (_) (same true))
  	       (Î» (_) (same sole)))))
	 sole
	 sole
	 (Î» (_) absurd))
       (same sole))))
#+end_src

So our quest continues.

* Distinguishability

But first, a side quest. Let's consider another definition, one that
seems promising.  We'll say that a type admits *complete distinguishability* if
all of its values are equal or distinguishable.

#+begin_src
(claim Distinguishability (â†’ U U))
(define Distinguishability
  (Î» (A)
     (Î  ((x A)
         (y A))
	(âˆ¨ (= A x y)
	   (â—‡ A x y)))))
#+end_src

It shouldn't be too surprising that having an equality decider is
equivalent to admitting complete distinguishability in Pie because of
â—‡â†’â‰ .  What's surprising (at least to me) is that this also holds in
minimal Pie, i.e., our ability to use construct an equality decider
from complete distinguishability does not depend on the principle
explosion.  In this sense, complete distinguishability is the
"correct" lowering of decidable equality into the minimal fragment so
if we want to be able to derive equality deciders.

As usual, one direction is easier than the other. If we have an
equality decider, we can use to distinguish unequals.

#+begin_src
(claim =trueâˆ¨=false
  (Î  ((b Bool))
     (âˆ¨ (= Bool b true)
        (= Bool b false))))
(define =trueâˆ¨=false
  (Î» (b)
     (ind-Bool
       b
       (Î» (b)
          (âˆ¨ (= Bool b true)
             (= Bool b false)))
      (left (same true))
      (right (same false)))))

(claim deciderâ¼â†’dist
  (Î  ((A U))
     (â†’ (Deciderâ¼ A)
        (Distinguishability A))))
(define deciderâ¼â†’dist
  (Î» (A deciderâ¼ x y)
     (ind-Either
       (=trueâˆ¨=false ((car deciderâ¼) x y))
       (Î» (_)
          (âˆ¨ (= A x y)
	     (â—‡ A x y)))
       (Î» (fxy=true)
          (left
	    ((cdr ((cdr deciderâ¼) (cons x y))) fxy=true)))
       (Î» (fxy=false)
          (right
	    (cons
	      ((car deciderâ¼) x)
	      (cons
	        ((car ((cdr deciderâ¼) (cons x x))) (same x))
		fxy=false)))))))
#+end_src

To prove that complete distinguishability implies a we can construct a
decider, it will be convenient to hand roll a new decider, the
analogous obvious decider for complete distinguishability.  We can
this prove that this decider is, in fact, a decider by taking
advantange of the distinguishability proof, which we can leverage to
avoid using explosion.

#+begin_src
(claim ==
  (Î  ((A U))
     (â†’ (Distinguishability A) A A Bool)))
(define ==
  (Î» (A dist x y)
     (left?
       (= A x y)
       (â—‡ A x y)
       (dist x y))))

(claim distâ†’=â†’==true
  (Î  ((A U)
      (dist (Distinguishability A))
      (x A)
      (y A))
     (â†’ (= A x y)
        (= Bool
	   (== A dist x y)
	   true))))
(define distâ†’=â†’==true
  (Î» (A dist x y x=y)
     (replace
       x=y
       (Î» (a)
          (= Bool
	     (== A dist x a)
	     true))
       (ind-Either
         (dist x x)
	 (Î» (e)
	    (= Bool
	       (left?
	         (= A x x)
		 (â—‡ A x x)
		 e)
	       true))
	 (Î» (_) (same true))
	 (Î» (xâ—‡x)
	    (trans
	      ; false = f x
	      (symm (cdr (cdr xâ—‡x)))
	      ; f x = true
	      (car (cdr xâ—‡x))))))))

(claim distâ†’==trueâ†’=
  (Î  ((A U)
      (dist (Distinguishability A))
      (x A)
      (y A))
     (â†’ (= Bool
	   (== A dist x y)
	   true)
	(= A x y))))
(define distâ†’==trueâ†’=
  (Î» (A dist x y)
     (ind-Either
       (dist x y)
       (Î» (e)
          (â†’ (= Bool
	       (left?
	         (= A x y)
	         (â—‡ A x y)
	         e)
	       true)
	     (= A x y)))
       (Î» (x=y _) x=y)
       (Î» (_ false=true)
          (explode-true=false
	    (symm false=true)
	    (= A x y))))))

(claim distâ†’deciderâ¼
  (Î  ((A U))
     (â†’ (Distinguishability A)
        (Deciderâ¼ A))))
(define distâ†’deciderâ¼
  (Î» (A dist)
     (cons
       (== A dist)
       (Î» (p)
          (cons
            (distâ†’=â†’==true A dist (car p) (cdr p))
            (distâ†’==trueâ†’= A dist (car p) (cdr p)))))))
#+end_src

This, of course, gets us nowhere on our quest to find a condition that
allows use to distinguish unequals, but its a digression through which
I couldn't help but take a detour.

* Strong Deciders

There are probably a couple other intermediate definitions we could
look at, but let's get to the punchline.  Looking back, our inability
use the obvious equality decider in minimal Pie came from our
inability to derive equalities for the output values of the decider.
A minimal definition of deciability should give us this power so we
don't need to appeal to explosion.

We'll say that a function ğ‘“ is a *strong decider* for the predicate ğ‘ƒ
if (ğ‘ƒ ğ‘) implies (ğ‘“ ğ‘) = true and Â¬(ğ‘ƒ ğ‘) implies (ğ‘“ ğ‘) = false.

#+begin_src
(claim Strong-Decides
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U)))
     U))
(define Strong-Decides
  (Î» (A f P)
     (Î  ((x A))
        (âˆ§ (â†’ (P x) (= Bool (f x) true))
           (â†’ (Â¬ (P x)) (= Bool (f x) false))))))

(claim Strong-Decider
  (Î  ((A U)
      (P (â†’ A U)))
     U))
(define Strong-Decider
  (Î» (A P)
     (Î£ ((f (â†’ A Bool)))
        (Strong-Decides A f P))))

(claim Strong-Decidesâ‚‚
  (Î  ((A U)
      (B U)
      (f (â†’ A B Bool))
      (P (â†’ A B U)))
     U))
(define Strong-Decidesâ‚‚
  (Î» (A B f P)
     (Strong-Decides
       (Pair A B)
       (uncurry A B Bool f)
       (Uncurryá´¾ A B P))))

(claim Strong-Deciderâ‚‚
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     U))
(define Strong-Deciderâ‚‚
  (Î» (A B P)
     (Î£ ((f (â†’ A B Bool)))
        (Strong-Decidesâ‚‚ A B f P))))

(claim Strong-Decidesâ¼
  (Î  ((A U)
      (f (â†’ A A Bool)))
     U))
(define Strong-Decidesâ¼
  (Î» (A f)
     (Strong-Decidesâ‚‚
       A
       A
       f
       (Î» (x y) (= A x y)))))

(claim Strong-Deciderâ¼ (â†’ U U))
(define Strong-Deciderâ¼
  (Î» (A)
     (Î£ ((f (â†’ A A Bool)))
        (Strong-Decidesâ¼ A f))))
#+end_src

Having a strong decider is equivalent to having a decider in vanilla
Pie, but we can see the "stress" this new definition puts on the
minimal fragment.  The only thing that blocks the equivalence in
minimal Pie is our inability to prove that a Boolean value that not
true is false.  It may be worth noting that this principle has
similarities to semi-classical principles like the [[https://en.wikipedia.org/wiki/Limited_principle_of_omniscience][Limited Principle
of Omnipotence]].

#+begin_src
(claim ind-âŠ¥â†’â‰ trueâ†’=false
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((b Bool))
        (â†’ (â‰  Bool b true)
	   (= Bool b false)))))
(define ind-âŠ¥â†’â‰ trueâ†’=false
  (Î» (ind-âŠ¥ b bâ‰ true)
     (ind-Either
       (=trueâˆ¨=false b)
       (Î» (_) (= Bool b false))
       (Î» (b=true)
          (ind-âŠ¥
	    (bâ‰ true b=true)
	    (= Bool b false)))
       (Î» (b=false) b=false))))

(claim âŸ¨â‰ trueâ†’=falseâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((b Bool))
        (â†’ (â‰  Bool b true)
	   (= Bool b false)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨â‰ trueâ†’=falseâŸ©â†’ind-âŠ¥
  (Î» (â‰ trueâ†’=false absurd)
     (explode-true=false
       (â‰ trueâ†’=false
         true
	 (Î» (_) absurd)))))

(claim ind-âŠ¥â†’decidesâ¼â†’strong-decidesâ¼
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (f (â†’ A A Bool)))
        (â†’ (Decidesâ¼ A f)
           (Strong-Decidesâ¼ A f)))))
(define ind-âŠ¥â†’decidesâ¼â†’strong-decidesâ¼
  (Î» (ind-âŠ¥ A f decidesâ¼ p)
     (cons
       (car (decidesâ¼ p))
       (Î» (xâ‰ y)
          (ind-âŠ¥â†’â‰ trueâ†’=false
            ind-âŠ¥
            (f (car p) (cdr p))
            (Î» (fxy=true)
               (xâ‰ y ((cdr (decidesâ¼ p)) fxy=true))))))))

(claim âŸ¨decidesâ¼â†’strong-decidesâ¼âŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (f (â†’ A A Bool)))
        (â†’ (Decidesâ¼ A f)
           (Strong-Decidesâ¼ A f)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨decidesâ¼â†’strong-decidesâ¼âŸ©â†’ind-âŠ¥
  (Î» (decidesâ¼â†’strong-decidesâ¼ absurd)
     (explode-true=false
       ((cdr
          (decidesâ¼â†’strong-decidesâ¼
            âŠ¤
 	    (Î» (_ _) true)
 	    (Î» (_)
 	       (cons
 	         (Î» (_) (same true))
 	         (Î» (_) (same sole))))
            (cons sole sole)))
         (Î» (_) absurd)))))
#+end_src

Finally, having a strong decider is not quite stronger than having a
decider in the minimal fragment, but it is in when taken in addition
with deciable equality.

#+begin_src
(claim decâ¼â†’strong-deciderâ¼â†’deciderâ¼
  (Î  ((A U))
     (â†’ (Decâ¼ A)
        (Strong-Deciderâ¼ A)
        (Deciderâ¼ A))))
(define decâ¼â†’strong-deciderâ¼â†’deciderâ¼
  (Î» (A decâ¼ strong-deciderâ¼)
     (cons
       (car strong-deciderâ¼)
       (Î» (p)
         (cons
           (car ((cdr strong-deciderâ¼) p))
           (Î» (fxy=true)
              (ind-Either
	        (decâ¼ p)
	        (Î» (_) (= A (car p) (cdr p)))
	        (Î» (x=y) x=y)
	        (Î» (xâ‰ y)
	           (explode-true=false
	             (trans
		       ; true = f (car p) (cdr p)
		       (symm fxy=true)
		       ; f (car p) (cdr p) = false
		       ((cdr ((cdr strong-deciderâ¼) p)) xâ‰ y))
		     (= A (car p) (cdr p)))))))))))
#+end_src
This implies that having a strong decider is strictly stronger than
having a decider in the /paraconsistent/ variant of Pie (i.e., with
excluded middle and without explosion).

* Concluding Remarks

Despite the convoluted nature of this story, the ending is simple: in
minimal Pie, if a type ğ´ has a strong equality decider, then it has
distinguishable unequals.

#+begin_src
(claim strong-deciderâ¼â†’â‰ â†’â—‡
  (Î  ((A U)
      (strong-deciderâ¼ (Strong-Deciderâ¼ A))
      (x A)
      (y A))
     (â†’ (â‰  A x y) (â—‡ A x y))))
(define strong-deciderâ¼â†’â‰ â†’â—‡
  (Î» (A strong-deciderâ¼ x y xâ‰ y)
     (cons
       ((car strong-deciderâ¼) x)
       (cons
         ((car ((cdr strong-deciderâ¼) (cons x x))) (same x))
	 ((cdr ((cdr strong-deciderâ¼) (cons x y))) xâ‰ y)))))
#+end_src

This is certainly one of those cases where the journey is worth more
than the destination.  The final definition seems /right/, in the
sense that the proof uses the data its given exactly as you would
expect.  But the value of this exercise comes from recognizing that
strong deciders are tightly connectioned with decidable equality.  And
this connection illuminates a nuanced heirarchy of possible
definitions of decidable equality which aren't visible in vanilla
Pie.

The last thing perhaps worth pointing out is one final definition:

#+begin_src
(claim Very-Strong-Decides
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U)))
     U))
(define Very-Strong-Decides
  (Î» (A f P)
     (Î  ((x A))
        (âˆ§ (â†” (P x) (= Bool (f x) true))
	   (â†” (Â¬ (P x)) (= Bool (f x) false))))))
#+end_src

If you're at being conscious of explosions, this seems to be the a
reasonably conservative definition which which yields an equivalent
definition of decidable equality in vanilla Pie.  The only curiosity
of this definition is that, in terms of what is /necessary/, there's
no need for f(x) = false to imply Â¬P(x).
