#+TITLE: Explosives and Distinguishers
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="myStyle.css" />
#+OPTIONS: html-style:nil H:1 num:nil
#+HTML_LINK_HOME: index.html

/*Abstract.* TODO/ Testing

This piece is contains quite a few (read: far too many) proofs in [[https://docs.racket-lang.org/pie/index.html][Pie]],
a simple, beautiful, but verbose dependently typed programming
language.[fn::TODO] Before getting started, a small logical interface
used throughout to make proofs more readable:

#+begin_src lisp
  #lang pie

  (claim âŠ¥ U)
  (define âŠ¥ Absurd)

  (claim âŠ¤ U)
  (define âŠ¤ Trivial)

  (claim Â¬ (â†’ U U))
  (define Â¬ (Î» (A) (â†’ A âŠ¥)))

  (claim âˆ§ (â†’ U U U))
  (define âˆ§ (Î» (A B) (Pair A B)))

  (claim âˆ¨ (â†’ U U U))
  (define âˆ¨ (Î» (A B) (Either A B)))

  (claim â†” (â†’ U U U))
  (define â†” (Î» (A B) (âˆ§ (â†’ A B) (â†’ B A))))

  (claim â‰  (Î  ((A U)) (â†’ A A U)))
  (define â‰  (Î» (A x y) (Â¬ (= A x y))))
#+end_src

I recently spent an inordinate amount of time thinking about Pie
formalizations of the following theorem:

#+begin_quote
/1 = 0 implies I am the Pope./
#+end_quote

I was interested primarily in proofs that could be carried out in the
minimal fragment of Pie, i.e., without the use of [[https://docs.racket-lang.org/pie/index.html#%28def._%28%28lib._pie%2Fmain..rkt%29._ind-.Absurd%29%29][~ind-Absurd~]], the
induction principle for the empty type which expresses the [[https://en.wikipedia.org/wiki/Principle_of_explosion][principle
of explosion]].

Working in this vein leads one naturally to a standard fact of
constructive mathematics: 1 = 0 is /explosive/ in the sense that
anything follows from it in the minimal fragment of Pie.[fn::See
Proposition 3.2 of Constructivism in Mathematics by Trolestra and van
Dalen.]

#+begin_src lisp
  (claim explode-1=0
    (â†’ (= Nat 1 0) (Î  ((A U)) A)))
  (define explode-1=0
    (Î» (1=0 A)
       (replace
         1=0
         (Î» (a) (which-Nat a A (Î» (_) âŠ¤)))
         sole)))
#+end_src

This leads one /further/ to another natural enough question: /which
equalities are explosive?/

* Distinguishers

Its straightforward enought to generalize the above proof to any fixed
pair of natural numbers.

#+begin_src
  (claim sub1 (â†’ Nat Nat))
  (define sub1
    (Î» (n)
       (which-Nat n 0 (Î» (n-1) n-1))))

  (claim âˆ¸ (â†’ Nat Nat Nat))
  (define âˆ¸
    (Î» (m n)
       (iter-Nat n m sub1)))

  (claim 5=7â†’1=0
    (â†’ (= Nat 5 7) (= Nat 1 0)))
  (define 5=7â†’1=0
    (Î» (5=7)
       (symm
         (cong
           5=7
  	 (the
  	   (â†’ Nat Nat)
  	   (Î» (n) (âˆ¸ n 6)))))))

  (claim explode-5=7
    (â†’ (= Nat 5 7) (Î  ((A U)) A)))
  (define explode-5=7
    (Î» (5=7)
       (explode-1=0 (5=7â†’1=0 5=7))))
#+end_src

It also works for the equality true = false, given the standard sum
type encoding of Booleans.

#+begin_src lisp
  (claim Bool U)
  (define Bool (Either âŠ¤ âŠ¤))

  (claim true Bool)
  (define true (left sole))

  (claim false Bool)
  (define false (right sole))

  (claim ind-Bool
    (Î  ((target Bool)
        (motive (â†’ Bool U))
        (true-case (motive true))
        (false-case (motive false)))
       (motive target)))
  (define ind-Bool
    (Î» (target motive true-case false-case)
       (ind-Either
         target
         motive
         (Î» (_) true-case)
         (Î» (_) false-case))))

  (claim boolâ†’nat (â†’ Bool Nat))
  (define boolâ†’nat
    (Î» (b) (ind-Bool b (Î» (_) Nat) 1 0)))

  (claim true=falseâ†’1=0
    (â†’ (= Bool true false) (= Nat 1 0)))
  (define true=falseâ†’1=0
    (Î» (true=false) (cong true=false boolâ†’nat)))

  (claim explode-true=false
    (â†’ (= Bool true false) (Î  ((A U)) A)))
  (define explode-true=false
    (Î» (true=false)
       (explode-1=0 (true=falseâ†’1=0 true=false))))
#+end_src

All we're really doing here is bootstrapping; if an equality implies
that 1 = 0 then it's explosive.  This is not so natural a condition,
but it hints at a definition: let's say boolean function ğ‘“ : ğ´ â†’ Bool
/distinguishes/ two values ğ‘ and ğ‘ if ğ‘“ ğ‘ is true and ğ‘“ ğ‘ is false.
Furthermore, ğ‘ and ğ‘ are /distinguishable/, written ğ‘ â—‡ ğ‘, if there
is a distinguisher for them.

#+begin_src lisp
  (claim Distinguishes
    (Î  ((A U)
        (f (â†’ A Bool)))
       (â†’ A A U)))
  (define Distinguishes
    (Î» (_ f x y)
       (âˆ§ (= Bool (f x) true)
          (= Bool (f y) false))))

  (claim â—‡
    (Î  ((A U))
       (â†’ A A U)))
  (define â—‡
    (Î» (A x y)
       (Î£ ((f (â†’ A Bool)))
          (Distinguishes A f x y))))

  ; the following are getters for â—‡

  (claim distinguisher-â—‡
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (â†’ A Bool)))
  (define distinguisher-â—‡
    (Î» (_ _ _ xâ—‡y)
       (car xâ—‡y)))

  (claim distinguishes-fst
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (= Bool
          (distinguisher-â—‡ A x y xâ—‡y x)
          true)))
  (define distinguishes-fst
    (Î» (_ _ _ xâ—‡y)
       (car (cdr xâ—‡y))))

  (claim distinguishes-snd
    (Î  ((A U)
        (x A)
        (y A)
        (xâ—‡y (â—‡ A x y)))
       (= Bool
          (distinguisher-â—‡ A x y xâ—‡y y)
          false)))
  (define distinguishes-snd
    (Î» (_ _ _ xâ—‡y)
       (cdr (cdr xâ—‡y))))
#+end_src

Distinguishability captures more generally what's going on in the case
of 5 = 7 and true = false.

#+begin_src lisp
  (claim â—‡â†’explodeâ¼
    (Î  ((A U)
        (x A)
        (y A))
       (â†’ (â—‡ A x y)
          (= A x y)
          (Î  ((B U)) B))))
  (define â—‡â†’explodeâ¼
    (Î» (A x y xâ—‡y x=y)
      (explode-true=false
        (trans
          ; true = f x
          (symm (distinguishes-fst A x y xâ—‡y))
          (trans
            ; f x = f y
            (cong x=y (distinguisher-â—‡ A x y xâ—‡y))
            ; f y = false
            (distinguishes-snd A x y xâ—‡y))))))
#+end_src

In other words, /any equality of distinguishable terms is explosive./

* Inequality

Distinguishability is a strictly stronger relation than inquality in
the minimal fragment of Pie.[fn::Moving forward, we'll take advantage
of the fact that the principle of explosion is not a theorem in the
minimal fragment of Pie: to show that any other claim is not a
theorem, it suffices to show that it implies explosion.]

#+begin_src lisp
  (claim â—‡â†’â‰ 
    (Î  ((A U)
        (x A)
        (y A))
       (â†’ (â—‡ A x y)
          (â‰  A x y))))
  (define â—‡â†’â‰ 
    (Î» (A x y xâ—‡y x=y)
       (â—‡â†’explodeâ¼ A x y xâ—‡y x=y âŠ¥)))

  (claim âŸ¨â‰ â†’â—‡âŸ©â†’ind-âŠ¥
    (â†’ (Î  ((A U)
           (x A)
           (y A))
          (â†’ (â‰  A x y)
             (â—‡ A x y)))
       (â†’ âŠ¥ Î  ((A U)) A))))
  (define âŸ¨â‰ â†’â—‡âŸ©â†’ind-âŠ¥
    (Î» (â‰ â†’â—‡ absurd)
       (â—‡â†’explodeâ¼
         âŠ¤
         sole
         sole
         (â‰ â†’â—‡
           âŠ¤
  	 sole
  	 sole
  	 (Î» (_) absurd))
         (same sole))))
#+end_src

We also can't prove â‰ â†’â—‡ full Pie but this isn't something that can be
witnessed within Pie itself, as it's a theorem in the classical
extension of Pie (more on this later). The principle â‰ â†’â—‡ has the
flavor of many well-studied semi-classical principles: it expresses
the ability to extract something constructive from a negation
proof.[fn::See TODO]

And we are led quite naturally to the real motivating question of this
piece: /For what types are unequal values distinguishable?/ And how
does the answer change depending on our system?

What I aim to demonstrate is that in all cases (minimal, constructive,
paraconsistent, classical) the following holds:

#+begin_quote
/If A admits decidable equality, then unqual values of type A are
distinguishable./
#+end_quote

What is most interesting is that the statement is sensitive to exactly
how decidable equality is defined.

* Decidability

A type ğ´ admits decidable equality if for any two values ğ‘â‚ and ğ‘â‚‚ of
type ğ´, we have ğ‘â‚ = ğ‘â‚‚ or ğ‘â‚ â‰  ğ‘â‚‚.  This can be seen as a restriction
of the law of excluded middle.  But the notion of decidability
originates in computability theory, where a predicate ğ‘ƒ is decidable
if there is a computable function ğ‘“ such that ğ‘“(ğ‘¥) = 1 if and only if
ğ‘ƒ(x) holds.  Through the Curry-Howard lens, these two concepts
correspond; a term ğ‘“ of type

#+begin_quote
~(Î  ((x A) (y A)) (âˆ¨ (= ğ´ ğ‘â‚ ğ‘â‚‚) (â‰  ğ´ ğ‘â‚ ğ‘â‚)))~
#+end_quote

is a computation where ~(f x y)~ evaluates to ~(left _)~ if x = y and
~(right _)~ otherwise.  We begin by formalizing this, but with a
twist: we'll work in the minimal fragment of Pie in order to
demonstrate that /this correspondence depends on the principle of
explosion/.

A type ğ´ (viewed through Curry-Howard lense) is *decidable* if either
ğ´ or Â¬ğ´ holds.  The law of excluded middle is equivalent to every type
being decidable.  We can use this baseline notion of decidability to
define decidability of predicates, up to decidable equality.  Note
that if we want to use binary predicates in their Curried form, we
need to uncurry them to express their decidability.

#+begin_src
(claim Decá´¾
  (Î  ((A U)
      (P (â†’ A U)))
     U))
(define Decá´¾
  (Î» (A P)
     (Î  ((x A)) (Dec (P x)))))

(claim Uncurryá´¾
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     (â†’ (Pair A B) U)))
(define Uncurryá´¾
  (Î» (_ _ P p)
     (P (car p) (cdr p))))

(claim Decá´¾Â²
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     U))
(define Decá´¾Â²
  (Î» (A B P)
     (Decá´¾ (Pair A B) (Uncurryá´¾ A B P))))

(claim Decâ¼ (â†’ U U))
(define Decâ¼
  (Î» (A)
     (Decá´¾Â²
       A
       A
       (Î» (x y) (= A x y)))))
#+end_src

The computability theoretic form of decidability can be expressed as
having a decider, i.e., the existence of a function which witnesses
the truth value of the predicate (we'll use ~true~ and ~false~ instead
of ~1~ and ~0~).

#+begin_src
(claim Decides
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U)))
     U))
(define Decides
  (Î» (A f P)
     (Î  ((x A))
        (â†” (P x)
	   (= Bool (f x) true)))))

(claim Decider
  (Î  ((A U)
      (P (â†’ A U)))
     U))
(define Decider
  (Î» (A P)
     (Î£ ((f (â†’ A Bool)))
        (Decides A f P))))

(claim uncurry
  (Î  ((A U)
      (B U)
      (C U))
     (â†’ (â†’ A B C)
        (â†’ (Pair A B) C))))
(define uncurry
  (Î» (_ _ _ f p)
     (f (car p) (cdr p))))

(claim Decidesâ‚‚
  (Î  ((A U)
      (B U)
      (f (â†’ A B Bool))
      (P (â†’ A B U)))
     U))
(define Decidesâ‚‚
  (Î» (A B f P)
     (Decides
       (Pair A B)
       (uncurry A B Bool f)
       (Uncurryá´¾ A B P))))

(claim Deciderâ‚‚
  (Î  ((A U)
      (B U)
      (P (â†’ A B U)))
     U))
(define Deciderâ‚‚
  (Î» (A B P)
     (Î£ ((f (â†’ A B Bool)))
        (Decidesâ‚‚ A B f P))))

(claim Decidesâ¼
  (Î  ((A U)
      (f (â†’ A A Bool)))
     U))
(define Decidesâ¼
  (Î» (A f)
     (Decidesâ‚‚
       A
       A
       f
       (Î» (x y) (= A x y)))))

(claim Deciderâ¼ (â†’ U U))
(define Deciderâ¼
  (Î» (A)
     (Î£ ((f (â†’ A A Bool)))
        (Decidesâ¼ A f))))
#+end_src

The easy direction: if a predicate ğ‘ƒ has a decider, then it is
decidable.  The proof: given ğ‘¥, ask the decider if ğ‘ƒ(ğ‘¥) or Â¬ğ‘ƒ(ğ‘¥).  We
break the proof up into two parts because working with Î£-types in Pie
is /not/ ergonomic.

#+begin_src
(claim decidesâ†’decá´¾-helper
  (Î  ((A U)
      (f (â†’ A Bool))
      (P (â†’ A U))
      (x A))
     (â†’ (â†” (P x) (= Bool (f x) true))
        (Dec (P x)))))
(define decidesâ†’decá´¾-helper
  (Î» (_ f P x)
     (ind-Bool
       (f x)
       (Î» (b)
          (â†’ (â†” (P x) (= Bool b true))
	     (Dec (P x))))
       (Î» (prf)
          (left ((cdr prf) (same true))))
       (Î» (prf)
          (right
	    (Î» (px)
	       (trueâ‰ false
	         (symm ((car prf) px)))))))))

(claim deciderâ†’decá´¾
  (Î  ((A U)
      (P (â†’ A U)))
     (â†’ (Decider A P)
        (Decá´¾ A P))))
(define deciderâ†’decá´¾
  (Î» (A P decider x)
     (decidesâ†’decá´¾-helper
       A
       (car decider)
       P
       x
       ((cdr decider) x))))
#+end_src

The hard direction (or, rather, the impossible direction in the
minimal setting): if ğ‘ƒ is decidable then it has a decider.  Now, we
can't /exactly/ show that this does not hold in minimal Pie; proving
things don't exist in a constructive setting is tricky.  But what
we're really after is the following: if ğ‘ƒ is decidable, then the
/obvious/ decider for ğ‘ƒ is, in fact, a decider.

The obvious decider is the one which is encoded in the proof of
decidability. We can define the decider generally over decidable
predicates (given a proof of decidability).

#+begin_src
(claim left?
  (Î  ((A U)
      (B U))
     (â†’ (Either A B)
        Bool)))
(define left?
  (Î» (_ _ e)
     (ind-Either
       e
       (Î» (_) Bool)
       (Î» (_) true)
       (Î» (_) false))))

(claim ?
  (Î  ((A U)
      (P (â†’ A U)))
     (â†’ (Decá´¾ A P) A Bool)))
(define ?
  (Î» (_ P decá´¾ x)
     (left?
       (P x)
       (Â¬ (P x))
       (decá´¾ x))))

(claim ?â‚‚
  (Î  ((A U)
      (B U)
      (P (â†’ A B U))
      (decá´¾Â² (Decá´¾Â² A B P)))
     (â†’ A B Bool)))
(define ?â‚‚
  (Î» (A B P decá´¾Â² x y)
     (?
       (Pair A B)
       (Uncurryá´¾ A B P)
       decá´¾Â²
       (cons x y))))

(claim â‰Ÿ
  (Î  ((A U))
     (â†’ (Decâ¼ A) A A Bool)))
(define â‰Ÿ
  (Î» (A) (?â‚‚ A A (Î» (x y) (= A x y)))))
#+end_src

Within the minimal fragment of Pie, if we know the value of this
decider on ğ‘, then we can derive proofs of the ğ‘ƒ(ğ‘) or Â¬ğ‘ƒ(ğ‘),
depending on that value.

#+begin_src
(claim p?=trueâ†’p
  (Î  ((A U)
      (P (â†’ A U))
      (decá´¾ (Decá´¾ A P))
      (x A))
     (â†’ (= Bool (? A P decá´¾ x) true)
        (P x))))
(define p?=trueâ†’p
  (Î» (_ P decá´¾ x)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (â†’ (= Bool
	        (left? (P x) (Â¬ (P x)) e)
	        true)
             (P x)))
       (Î» (px _) px)
       (Î» (_ false=true)
          (explode-true=false
	    (symm false=true)
	    (P x))))))

(claim p?=falseâ†’Â¬p
  (Î  ((A U)
      (P (â†’ A U))
      (decá´¾ (Decá´¾ A P))
      (x A))
     (â†’ (= Bool
           (? A P decá´¾ x)
	   false)
        (Â¬ (P x)))))
(define p?=falseâ†’Â¬p
  (Î» (_ P decá´¾ x)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (â†’ (= Bool
	        (left? (P x) (Â¬ (P x)) e)
		false)
             (Â¬ (P x))))
       (Î» (_ true=false)
          (explode-true=false
	    true=false
	    (Â¬ (P x))))
       (Î» (Â¬px _) Â¬px))))
#+end_src

What we /can't/ do within minimal Pie is determine the value of the
decider itself given ğ‘ƒ(ğ‘) or Â¬ğ‘ƒ(ğ‘).  For example, ğ‘ƒ(ğ‘) implies the
equality (? ğ‘ƒ ğ‘) = true given the principle of explosion, but this
implication also /implies/ the principle of explosion.  This
ultimately comes down to the fact that there isn't much we can do in
the Â¬ğ‘ƒ(ğ‘) branch of the decidability of ğ‘ƒ except explode it with our
assumption ğ‘ƒ(ğ‘).

#+begin_src lisp
(claim ind-âŠ¥â†’pâ†’p?=true
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (P x)
	   (= Bool
	      (? A P decá´¾ x)
	      true)))))
(define ind-âŠ¥â†’pâ†’p?=true
  (Î» (ind-âŠ¥ _ P decá´¾ x px)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (= Bool
	     (left? (P x) (Â¬ (P x)) e)
	     true))
       (Î» (_) (same true))
       (Î» (Â¬px)
          (ind-âŠ¥â†’explode
	    ind-âŠ¥
	    (P x)
            Â¬px
	    px
	    (= Bool false true))))))

(claim âŸ¨pâ†’p?=trueâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (P x)
	   (= Bool
	      (? A P decá´¾ x)
	      true)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨pâ†’p?=trueâŸ©â†’ind-âŠ¥
  (Î» (pâ†’p?=true absurd)
     (explode-true=false
       (symm
         (pâ†’p?=true
           âŠ¤
           (Î» (_) âŠ¤)
           (Î» (_) (right (Î» (_) absurd)))
           sole
           sole)))))

(claim ind-âŠ¥â†’Â¬pâ†’p?=false
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (Â¬ (P x))
	   (= Bool
	      (? A P decá´¾ x)
	      false)))))
(define ind-âŠ¥â†’Â¬pâ†’p?=false
  (Î» (ind-âŠ¥ _ P decá´¾ x Â¬px)
     (ind-Either
       (decá´¾ x)
       (Î» (e)
          (= Bool
	     (left? (P x) (Â¬ (P x)) e)
	     false))
       (Î» (px)
          (ind-âŠ¥â†’explode
	    ind-âŠ¥
	    (P x)
	    Â¬px
	    px
	    (= Bool true false)))
       (Î» (_) (same false)))))

(claim âŸ¨Â¬pâ†’p?=falseâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P))
	 (x A))
	(â†’ (Â¬ (P x))
	   (= Bool
	      (? A P decá´¾ x)
	      false)))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨Â¬pâ†’p?=falseâŸ©â†’ind-âŠ¥
  (Î» (Â¬pâ†’p?=false absurd)
     (explode-true=false
       (Â¬pâ†’p?=false
         âŠ¤
	 (Î» (_) âŠ¥)
         ; artificial proof of negation
	 (Î» (_) (left absurd))
	 sole
	 (Î» (absurd) absurd)))))
#+end_src

Another theme that comes up here: in almost all cases, the ~Trivial~
type is sufficient to find a counterexample in minimal Pie of a given
principle.  Most come down to an artificial proof of a negation using
our ~Absurd~ assumption in the principle of explosion (see the last
example above).

All of this amounts to the fact that having a decider is a strictly
stronger notion of decidability within minimal Pie (in the sense that
we cannot prove that the obvious decider is a decider).

#+begin_src
(claim ind-âŠ¥â†’decá´¾â†’decides
  (â†’ (â†’ âŠ¥ (Î  ((A U)) A))
     (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P)))
	(Decides A (? A P decá´¾) P))))
(define ind-âŠ¥â†’decá´¾â†’decides
  (Î» (ind-absurd A P decá´¾ x)
     (cons
       (ind-âŠ¥â†’pâ†’p?=true
         ind-absurd
	 A
	 P
	 decá´¾
	 x)
       (p?=trueâ†’p
         A
	 P
	 decá´¾
	 x))))

(claim âŸ¨decá´¾â†’decidesâŸ©â†’ind-âŠ¥
  (â†’ (Î  ((A U)
         (P (â†’ A U))
	 (decá´¾ (Decá´¾ A P)))
	(Decides A (? A P decá´¾) P))
     (â†’ âŠ¥ (Î  ((A U)) A))))
(define âŸ¨decá´¾â†’decidesâŸ©â†’ind-âŠ¥
  (Î» (decá´¾â†’decides absurd)
     (explode-true=false
       (symm
         ((car
	    ((decá´¾â†’decides
	       âŠ¤
	       (Î» (_) âŠ¤)
	       (Î» (_) (right (Î» (_) absurd))))
	      sole))
	    sole)))))
#+end_src

But even though having a decider is stronger, it's not sufficient to
prove distinguishability from inequality in minimal Pie.

By virtue of having defined everything in terms of general
decidability, we get immediately as a corollary our first result, that
decidable equality implies distinguishable unequals in classical Pie.
Note again that the antecedent here is vacuous because it a special
case of the law of excluded middle.  The distinguisher is the partial
application of the obvious decider.
